### PR TITLE
Use XCTestCase instead of SenTestCase.

### PR DESCRIPTION
**Pull request by cwp**
Works nicely with Xcode 5's new test support.

### CODE REVIEW

**Comment by marianoabdala** [comment]
Hey, @cwp, thanks for the update. I forgot to do it myself when iOS 7 came out.

I'll review and test tonight, but it looks good at first sight.

**Comment by marianoabdala** [comment]
The sample project is not compiling correctly. Could you please review?

**Comment by cwp** [comment]
On Wed, Nov 27, 2013 at 5:38 PM, Mariano Abdala notifications@github.comwrote:

> The sample project is not compiling correctly. Could you please review?

Sure.

**Comment by cwp** [comment]
Obsolete, I guess.

**Pull request closed without merging**
